# Generated by Django 5.2.10 on 2026-02-02 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='المبلغ')),
                ('ref_last_4', models.CharField(max_length=4, verbose_name='آخر 4 أرقام')),
                ('transaction_date', models.DateField(verbose_name='تاريخ الإشعار')),
                ('type', models.CharField(choices=[('in', 'وارد'), ('out', 'صادر')], max_length=3, verbose_name='النوع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
            },
        ),
    ]
