# Generated by Django 5.2.10 on 2026-03-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersettings',
            old_name='privacy_mode',
            new_name='use_currency_symbols',
        ),
    ]
