# Generated by Django 5.2.10 on 2026-07-27 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_privacy_mode_usersettings_use_currency_symbols'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
